const AppContextActions = {
    SET_SELECTED_SPECIFICATION: "SET_SELECTED_SPECIFICATION",
    LOAD_SPECIFICATIONS: "LOAD_SPECIFICATIONS",
    ADD_NEW_RESPONSE: "ADD_NEW_RESPONSE"
};

export default AppContextActions;
