swagger: '2.0'
info:
  title: wade-rat-mihtei-rezciopan WADE-RAT|Mihtei-Rezciopan - Test API
  description: |-
    ### Simple test API for the RAT project

    This file represents the OpenAPI 2.0 specification of the [RAT WADe Project Test API](https://profs.info.uaic.ro/~busaco/teach/courses/wade/projects/index.html) of Fall 2021 made by Cioata Matei-Alexandru, Lipan Radu-Matei, Rezmerita Mihnea-Ioan. The API described below serves for testing purposes and helps creating a proof of concept for the RAT project.
  version: 1.0.0
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "X-API-Key"
    in: "header"
schemes:
  - https
produces:
  - application/json
paths:
  /feline:
    get:
      tags:
        - cats
      summary: Lists all felines with specified filters
      operationId: felinesQuery
      parameters:
        - name: id
          in: query
          required: false
          description: The ID of the feline
          type: string
        - name: feeling
          in: query
          required: false
          description: The emotional state of the feline
          type: string
        - name: color
          in: query
          required: false
          description: The color of the feline's fur
          type: string
        - name: muscle
          in: query
          required: false
          description: The feline's physical state
          type: string
        - name: members
          in: query
          required: false
          description: The number of legs that the feline has
          type: string
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
    put:
      tags:
        - cats
      summary: Replaces and existing feline with another one.
      operationId: felinesPut
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/FelineRequestBody'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '412':
          description: Precondition Failed
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
      x-codegen-request-body-name: body
    patch:
      tags:
        - cats
      summary: Update an existing feline's attributes.
      operationId: felinesPatch
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/FelineRequestBody'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '412':
          description: Precondition Failed
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
      x-codegen-request-body-name: body
    delete:
      tags:
        - cats
      summary: Delete all felines with given attributes.
      operationId: felinesDelete
      parameters:
        - name: id
          in: query
          required: false
          description: The ID of the feline
          type: string
        - name: feeling
          in: query
          required: false
          description: The emotional state of the feline
          type: string
        - name: color
          in: query
          required: false
          description: The color of the feline's fur
          type: string
        - name: muscle
          in: query
          required: false
          description: The feline's physical state
          type: string
        - name: members
          in: query
          required: false
          description: The number of legs that the feline has
          type: string
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '412':
          description: Precondition Failed
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
      x-codegen-request-body-name: body
    options:
      tags:
        - cats
      operationId: catsOptions
      responses:
        '204':
          description: A successful response
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
  /bug:
    delete:
      tags:
        - bugs
      summary: Deletes all bugs with specified filters
      operationId: bugsDelete
      parameters:
        - name: id
          in: query
          required: false
          description: The ID of the bug
          type: string
        - name: feeling
          in: query
          required: false
          description: The emotional state that the bug causes
          type: string
        - name: color
          in: query
          required: false
          description: The color of the bug
          type: string
        - name: members
          in: query
          required: false
          description: The number of legs that the bug has
          type: string
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
    options:
      tags:
        - bugs
      operationId: bugsOptions
      responses:
        '204':
          description: A successful response
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
  /weapon:
    post:
      tags:
        - weapons
      summary: Creates a new weapon with specified attributes.
      operationId: weaponsCreation
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/WeaponRequestBody'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
    put:
      tags:
        - weapons
      summary: Replaces and existing weapon with another one.
      operationId: weaponsPut
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: '#/definitions/WeaponRequestBody'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/GenericResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '412':
          description: Precondition Failed
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
      x-codegen-request-body-name: body
    options:
      tags:
        - weapons
      operationId: weaponsOptions
      responses:
        '204':
          description: A successful response
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
      x-google-backend:
        address: https://europe-west1-avid-airway-337117.cloudfunctions.net/bugsCatsWeapons
        path_translation: APPEND_PATH_TO_ADDRESS
definitions:
    FelineRequestBody:
      type: object
      properties:
        id:
          type: string
        feeling:
          type: string
        color:
          type: string
        muscle:
          type: string
        members:
          type: string
    BugRequestBody:
      type: object
      properties:
        id:
          type: string
        feeling:
          type: string
        color:
          type: string
        members:
          type: string
    WeaponRequestBody:
      type: object
      properties:
        id:
          type: string
        force:
          type: string
        color:
          type: string
    GenericResponse:
      type: object
      properties:
        message:
          type: string
    Dictionary:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
